import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  workshop101: [
    {
      type: 'category',
      label: '101 — Foundations & STAR',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'workshop-101/index'},
      items: [
        {type: 'autogenerated', dirName: 'workshop-101'},
      ],
    },
  ],
  workshop201: [
    {
      type: 'category',
      label: '201 — Principles & Skills',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'workshop-201/index'},
      items: [
        {type: 'autogenerated', dirName: 'workshop-201'},
      ],
    },
  ],
  workshop301: [
    {
      type: 'category',
      label: '301 — Advanced',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'workshop-301/index'},
      items: [
        {type: 'autogenerated', dirName: 'workshop-301'},
      ],
    },
  ],
};

export default sidebars;
